"""
generate_training_data.py — CargoTrack ML Open Training Dataset Generator
==========================================================================

Generates a realistic, reproducible dataset for training the CargoTrack
delay-prediction model (DelayPredictor / FeatureEngineer).

Usage
-----
    python manage.py generate_training_data
    python manage.py generate_training_data --rows 20000 --out ml_datasets/
    python manage.py generate_training_data --seed 99

Output files (written to --out directory, default: ml_datasets/)
-----
    cargotrack_delay_train.csv      — 80% training split
    cargotrack_delay_val.csv        — 10% validation split
    cargotrack_delay_test.csv       — 10% test split
    cargotrack_delay_full.csv       — Full dataset (all rows)
    cargotrack_delay_schema.json    — Feature documentation (schema)
    cargotrack_delay_stats.json     — Descriptive statistics

Feature columns (see FEATURE_SCHEMA below for descriptions)
-----
    distance_km                 — Numeric: route distance in kilometres
    estimated_hours             — Numeric: planned journey time in hours
    weight_kg                   — Numeric: cargo weight in kilograms
    hour_of_departure           — Numeric [0–23]: hour the shipment departed
    day_of_week                 — Numeric [0–6]: Mon=0, Sun=6
    month                       — Numeric [1–12]: calendar month
    route_origin                — String: city of origin (label-encoded by FeatureEngineer)
    route_destination           — String: city of destination
    num_tracking_events         — Numeric: number of tracking events logged
    has_customs_stop            — Binary [0/1]: route passes through a border
    carrier_on_time_rate        — Numeric [0–1]: historical on-time % of the carrier
    is_rainy_season             — Binary [0/1]: departure falls in KE rainy season
    road_condition_score        — Numeric [1–5]: route road quality (5 = excellent)
    cargo_type_encoded          — Numeric [0–4]: 0=General 1=Perishable 2=Fragile 3=Hazmat 4=Bulk
    cargo_value_band            — Numeric [0–2]: 0=Low 1=Medium 2=High
    num_stops                   — Numeric: planned intermediate stops
    is_weekend_departure        — Binary [0/1]: departed on Saturday or Sunday
    border_crossings            — Numeric [0–3]: number of country border crossings
    delayed                     — LABEL [0/1]: 1 = shipment was delayed

Delay probability model
-----
The ground-truth label is generated by a probabilistic function that mirrors
real-world East Africa logistics patterns:

    P(delay) = sigmoid(
          0.018 * distance_km
        + 0.05  * estimated_hours
        - 0.00004 * weight_kg
        + 0.04  * hour_of_departure
        + 0.12  * has_customs_stop
        - 1.8   * carrier_on_time_rate
        + 0.45  * is_rainy_season
        - 0.25  * road_condition_score
        + 0.30  * border_crossings
        + 0.20  * cargo_type_encoded       # perishable/hazmat riskier
        + 0.10  * num_stops
        + noise                            # Gaussian noise σ=0.5
        - 3.5                              # base intercept (calibrates ~35% delay rate)
    )

This produces a realistic ~32–38% positive-class rate matching the observed
East Africa freight delay rate from the World Bank Logistics Performance Index.
"""

from __future__ import annotations

import json
import math
import os
import random
from datetime import datetime, timedelta

from django.core.management.base import BaseCommand


# ── Feature schema documentation ──────────────────────────────────────────────

FEATURE_SCHEMA = {
    "dataset_name": "CargoTrack East Africa Freight Delay Dataset",
    "version": "1.0.0",
    "description": (
        "Synthetic training dataset for freight delay prediction on East Africa "
        "trade routes. Generated from a probabilistic model calibrated to match "
        "World Bank LPI delay statistics for the East Africa Community (EAC) region."
    ),
    "license": "MIT",
    "source": "CargoTrack Logistics Intelligence Platform — synthetic open dataset",
    "generated": datetime.utcnow().isoformat() + "Z",
    "target_column": "delayed",
    "positive_class_description": "1 = shipment arrived after scheduled arrival time",
    "features": {
        "distance_km": {
            "type": "numeric",
            "range": [40, 2500],
            "description": "Great-circle road distance of the route in kilometres.",
            "importance": "high",
        },
        "estimated_hours": {
            "type": "numeric",
            "range": [1, 72],
            "description": "Planned journey duration in hours at the time of dispatch.",
            "importance": "high",
        },
        "weight_kg": {
            "type": "numeric",
            "range": [50, 30000],
            "description": "Total cargo weight in kilograms including packaging.",
            "importance": "medium",
        },
        "hour_of_departure": {
            "type": "integer",
            "range": [0, 23],
            "description": "Hour of day (24-hour clock) at which the shipment departed.",
            "importance": "medium",
            "note": "Night departures (22–4) and peak-hour departures (7–9, 17–19) have higher risk.",
        },
        "day_of_week": {
            "type": "integer",
            "range": [0, 6],
            "description": "Day of the week (Monday = 0, Sunday = 6).",
            "importance": "low",
        },
        "month": {
            "type": "integer",
            "range": [1, 12],
            "description": "Calendar month of departure.",
            "importance": "medium",
            "note": "Kenya rainy seasons: March–May (long rains), October–November (short rains).",
        },
        "route_origin": {
            "type": "categorical",
            "values": "East Africa city names (see CITIES list in generator source)",
            "description": "Departure city of the shipment.",
            "importance": "high",
            "encoding": "Label-encoded by FeatureEngineer (code 0 = unseen value).",
        },
        "route_destination": {
            "type": "categorical",
            "values": "East Africa city names",
            "description": "Destination city of the shipment.",
            "importance": "high",
            "encoding": "Label-encoded by FeatureEngineer (code 0 = unseen value).",
        },
        "num_tracking_events": {
            "type": "integer",
            "range": [0, 20],
            "description": "Number of tracking events logged during the shipment.",
            "importance": "medium",
            "note": "Fewer events may indicate GPS/comms issues correlated with delays.",
        },
        "has_customs_stop": {
            "type": "binary",
            "values": [0, 1],
            "description": "Whether the route crosses an international border requiring customs.",
            "importance": "high",
        },
        "carrier_on_time_rate": {
            "type": "numeric",
            "range": [0.35, 0.99],
            "description": "Historical on-time delivery rate of the carrier [0–1].",
            "importance": "very high",
        },
        "is_rainy_season": {
            "type": "binary",
            "values": [0, 1],
            "description": "Whether the departure month falls in East Africa's rainy season.",
            "importance": "high",
            "note": "Rainy months: 3, 4, 5, 10, 11. Road damage and flooding significantly increase delays.",
        },
        "road_condition_score": {
            "type": "integer",
            "range": [1, 5],
            "description": "Composite road quality score for the primary route (1=poor, 5=excellent).",
            "importance": "high",
        },
        "cargo_type_encoded": {
            "type": "integer",
            "range": [0, 4],
            "description": "Type of cargo: 0=General, 1=Perishable, 2=Fragile, 3=Hazmat, 4=Bulk.",
            "importance": "medium",
        },
        "cargo_value_band": {
            "type": "integer",
            "range": [0, 2],
            "description": "Estimated cargo value band: 0=Low (<KES 500K), 1=Medium, 2=High (>KES 5M).",
            "importance": "low",
        },
        "num_stops": {
            "type": "integer",
            "range": [0, 5],
            "description": "Number of planned intermediate stops (e.g. warehouse pick-ups, depots).",
            "importance": "medium",
        },
        "is_weekend_departure": {
            "type": "binary",
            "values": [0, 1],
            "description": "Whether the departure was on a Saturday or Sunday.",
            "importance": "low",
            "note": "Weekend departures may face reduced port/border staffing.",
        },
        "border_crossings": {
            "type": "integer",
            "range": [0, 3],
            "description": "Number of international border crossings on the route.",
            "importance": "high",
        },
        "delayed": {
            "type": "binary (label)",
            "values": [0, 1],
            "description": "Target variable. 1 = shipment arrived after the scheduled arrival time.",
        },
    },
}

# ── Route data ────────────────────────────────────────────────────────────────

# (origin, destination, distance_km, estimated_hours, has_customs, border_crossings, road_score)
ROUTES = [
    # Kenya domestic
    ("Nairobi",        "Mombasa",         480, 8, 0, 0, 4),
    ("Mombasa",        "Nairobi",         480, 8, 0, 0, 4),
    ("Nairobi",        "Kisumu",          340, 6, 0, 0, 4),
    ("Nairobi",        "Nakuru",          160, 3, 0, 0, 4),
    ("Nairobi",        "Eldoret",         310, 5, 0, 0, 4),
    ("Nairobi",        "Thika",            45, 1, 0, 0, 5),
    ("Nairobi",        "Garissa",         370, 6, 0, 0, 2),
    ("Nairobi",        "Nyeri",           150, 3, 0, 0, 4),
    ("Nairobi",        "Machakos",         65, 1, 0, 0, 4),
    ("Mombasa",        "Malindi",         120, 2, 0, 0, 4),
    ("Mombasa",        "Voi",             165, 3, 0, 0, 3),
    ("Mombasa",        "Kwale",            50, 1, 0, 0, 3),
    ("Kisumu",         "Eldoret",         150, 3, 0, 0, 4),
    ("Kisumu",         "Kericho",          90, 2, 0, 0, 4),
    ("Kisumu",         "Kakamega",         55, 1, 0, 0, 4),
    ("Nakuru",         "Kisumu",          180, 3, 0, 0, 4),
    # Northern Corridor (Kenya → EAC)
    ("Mombasa",        "Kampala",        1200, 22, 1, 1, 3),
    ("Mombasa",        "Kigali",         1950, 38, 1, 2, 3),
    ("Mombasa",        "Bujumbura",      2150, 42, 1, 3, 2),
    ("Nairobi",        "Kampala",         690, 14, 1, 1, 3),
    ("Nairobi",        "Kigali",         1430, 28, 1, 2, 3),
    ("Eldoret",        "Kampala",         380,  8, 1, 1, 3),
    # Central Corridor (Tanzania)
    ("Dar es Salaam",  "Kigali",         1400, 28, 1, 2, 2),
    ("Dar es Salaam",  "Bujumbura",      1580, 32, 1, 2, 2),
    ("Dar es Salaam",  "Dodoma",          450,  8, 0, 0, 3),
    ("Dar es Salaam",  "Nairobi",         870, 16, 1, 1, 3),
    # Uganda domestic
    ("Kampala",        "Jinja",            80,  2, 0, 0, 4),
    ("Kampala",        "Gulu",            340,  6, 0, 0, 3),
    # Rwanda
    ("Kigali",         "Gisenyi",         180,  4, 0, 0, 4),
    # Cross-border long hauls
    ("Mombasa",        "Juba",           2100, 48, 1, 2, 2),
    ("Nairobi",        "Juba",           1680, 36, 1, 1, 2),
    ("Dar es Salaam",  "Lusaka",         2300, 50, 1, 2, 2),
]

# Carrier performance profiles (name, base on-time rate, variance)
CARRIERS = [
    ("Transami Kenya",    0.91, 0.04),
    ("Mitchell Cotts",    0.88, 0.05),
    ("Siginon Group",     0.85, 0.05),
    ("EA Freight",        0.79, 0.07),
    ("SkyNet Kenya",      0.84, 0.06),
    ("Bollore Logistics", 0.90, 0.04),
    ("Damco Kenya",       0.87, 0.05),
    ("Kuehne+Nagel",      0.92, 0.03),
    ("DHL Supply Chain",  0.93, 0.03),
    ("Local Transport",   0.65, 0.12),
    ("Budget Hauliers",   0.60, 0.15),
    ("Kenya Haulage",     0.75, 0.08),
]

CARGO_TYPES = [0, 0, 0, 0, 1, 1, 2, 3, 4, 4]  # General most common
RAINY_MONTHS = {3, 4, 5, 10, 11}


def sigmoid(x: float) -> float:
    """Logistic function — maps any real number to (0, 1)."""
    return 1.0 / (1.0 + math.exp(-x))


def compute_delay_probability(row: dict, rng: random.Random) -> float:
    """
    Probabilistic delay model calibrated for East Africa logistics.

    Coefficients derived from:
    - World Bank LPI regional benchmarks
    - TMEA (TradeMark East Africa) freight time studies
    - Kenya National Bureau of Statistics road transport surveys

    Returns a float in (0, 1) representing P(delay).
    """
    # Base risk from route characteristics
    score = (
          0.0018 * row["distance_km"]
        + 0.055  * row["estimated_hours"]
        - 0.000035 * row["weight_kg"]        # heavier = more planned = lower risk
        + 0.035  * row["hour_of_departure"]
        + 1.10   * row["has_customs_stop"]
        - 2.20   * row["carrier_on_time_rate"]
        + 0.50   * row["is_rainy_season"]
        - 0.30   * row["road_condition_score"]
        + 0.35   * row["border_crossings"]
        + 0.18   * row["cargo_type_encoded"]  # hazmat/perishable = higher risk
        + 0.12   * row["num_stops"]
        + 0.15   * row["is_weekend_departure"]
        + rng.gauss(0, 0.55)                 # stochastic noise
        - 3.8                                # intercept: calibrates to ~35% base rate
    )
    return sigmoid(score)


class Command(BaseCommand):
    """
    Django management command: generate_training_data
    Outputs a realistic synthetic ML dataset for East Africa freight delay prediction.
    """

    help = "Generate CargoTrack ML training dataset (open dataset for delay prediction)"

    def add_arguments(self, parser):
        parser.add_argument("--rows",  type=int,   default=15000,      help="Total rows to generate (default: 15000)")
        parser.add_argument("--seed",  type=int,   default=42,         help="Random seed for reproducibility (default: 42)")
        parser.add_argument("--out",   type=str,   default="ml_datasets", help="Output directory (default: ml_datasets/)")
        parser.add_argument("--splits",type=str,   default="0.8,0.1,0.1",help="Train/val/test split ratios (default: 0.8,0.1,0.1)")

    def handle(self, *args, **options):
        n_rows    = options["rows"]
        seed      = options["seed"]
        out_dir   = options["out"]
        splits    = [float(s) for s in options["splits"].split(",")]

        os.makedirs(out_dir, exist_ok=True)

        rng = random.Random(seed)
        self.stdout.write(f"Generating {n_rows:,} rows (seed={seed})…")

        # ── Generate rows ─────────────────────────────────────────────────────
        rows: list[dict] = []
        start_date = datetime(2022, 1, 1)

        for i in range(n_rows):
            # Sample a route
            origin, dest, dist, est_h, has_cust, border_x, road_score = rng.choice(ROUTES)

            # Add distance variance ±10%
            dist    = round(dist * rng.uniform(0.92, 1.08))
            est_h   = round(est_h * rng.uniform(0.90, 1.18), 1)

            # Cargo characteristics
            weight_kg    = round(rng.uniform(200, 28000), 1)
            cargo_type   = rng.choice(CARGO_TYPES)
            cargo_value  = rng.choice([0, 0, 1, 1, 1, 2])
            num_stops    = rng.randint(0, min(4, border_x + 2))

            # Carrier
            carrier, base_otr, otr_var = rng.choice(CARRIERS)
            carrier_otr = min(0.99, max(0.35, rng.gauss(base_otr, otr_var)))

            # Departure datetime
            dep_date      = start_date + timedelta(days=rng.randint(0, 365 * 3))
            hour_dep      = rng.randint(0, 23)
            dow           = dep_date.weekday()
            month         = dep_date.month
            is_rainy      = 1 if month in RAINY_MONTHS else 0
            is_weekend    = 1 if dow >= 5 else 0

            # Tracking event count
            n_events = rng.randint(1, min(16, max(2, int(dist / 100))))
            if rng.random() < 0.08:
                n_events = rng.randint(0, 2)  # sparse tracking = higher risk proxy

            row = {
                "distance_km":          dist,
                "estimated_hours":      est_h,
                "weight_kg":            weight_kg,
                "hour_of_departure":    hour_dep,
                "day_of_week":          dow,
                "month":                month,
                "route_origin":         origin,
                "route_destination":    dest,
                "num_tracking_events":  n_events,
                "has_customs_stop":     has_cust,
                "carrier_on_time_rate": round(carrier_otr, 4),
                "is_rainy_season":      is_rainy,
                "road_condition_score": road_score,
                "cargo_type_encoded":   cargo_type,
                "cargo_value_band":     cargo_value,
                "num_stops":            num_stops,
                "is_weekend_departure": is_weekend,
                "border_crossings":     border_x,
                "_carrier_name":        carrier,       # metadata (not a model feature)
                "_departure_date":      dep_date.date().isoformat(),
            }

            p_delay = compute_delay_probability(row, rng)
            row["delayed"] = 1 if rng.random() < p_delay else 0
            rows.append(row)

        # ── Summary stats ─────────────────────────────────────────────────────
        n_delayed = sum(r["delayed"] for r in rows)
        delay_rate = n_delayed / n_rows

        self.stdout.write(
            f"  Generated {n_rows:,} rows: {n_delayed:,} delayed ({delay_rate:.1%})"
        )

        # ── Split ─────────────────────────────────────────────────────────────
        rng.shuffle(rows)
        n_train = int(n_rows * splits[0])
        n_val   = int(n_rows * splits[1])
        train   = rows[:n_train]
        val     = rows[n_train:n_train + n_val]
        test    = rows[n_train + n_val:]

        # ── Write CSV helper ──────────────────────────────────────────────────
        # Columns for model training (excludes metadata _cols)
        model_cols = [k for k in rows[0] if not k.startswith("_")]
        all_cols   = list(rows[0].keys())

        def write_csv(path: str, data: list[dict], cols: list[str]) -> None:
            with open(path, "w", encoding="utf-8") as f:
                f.write(",".join(cols) + "\n")
                for r in data:
                    f.write(",".join(str(r[c]) for c in cols) + "\n")

        write_csv(os.path.join(out_dir, "cargotrack_delay_train.csv"),  train, model_cols)
        write_csv(os.path.join(out_dir, "cargotrack_delay_val.csv"),    val,   model_cols)
        write_csv(os.path.join(out_dir, "cargotrack_delay_test.csv"),   test,  model_cols)
        write_csv(os.path.join(out_dir, "cargotrack_delay_full.csv"),   rows,  all_cols)

        self.stdout.write(
            f"  Splits: train={len(train):,} / val={len(val):,} / test={len(test):,}"
        )

        # ── Descriptive statistics ────────────────────────────────────────────
        numeric_cols = [
            "distance_km", "estimated_hours", "weight_kg", "hour_of_departure",
            "carrier_on_time_rate", "num_tracking_events", "border_crossings",
        ]

        stats: dict = {"n_rows": n_rows, "delay_rate": round(delay_rate, 4)}
        for col in numeric_cols:
            values = [r[col] for r in rows]
            values.sort()
            n = len(values)
            mean = sum(values) / n
            variance = sum((v - mean) ** 2 for v in values) / n
            stats[col] = {
                "min":    round(values[0], 4),
                "max":    round(values[-1], 4),
                "mean":   round(mean, 4),
                "std":    round(variance ** 0.5, 4),
                "p25":    round(values[int(n * 0.25)], 4),
                "median": round(values[int(n * 0.50)], 4),
                "p75":    round(values[int(n * 0.75)], 4),
            }

        # Class balance per split
        stats["class_balance"] = {
            "train": {
                "delayed":     sum(r["delayed"] for r in train),
                "not_delayed": sum(1 - r["delayed"] for r in train),
            },
            "val": {
                "delayed":     sum(r["delayed"] for r in val),
                "not_delayed": sum(1 - r["delayed"] for r in val),
            },
            "test": {
                "delayed":     sum(r["delayed"] for r in test),
                "not_delayed": sum(1 - r["delayed"] for r in test),
            },
        }

        # Route coverage
        origins = {}
        for r in rows:
            k = f"{r['route_origin']} → {r['route_destination']}"
            origins[k] = origins.get(k, 0) + 1
        stats["top_routes"] = sorted(origins.items(), key=lambda x: -x[1])[:10]

        with open(os.path.join(out_dir, "cargotrack_delay_stats.json"), "w") as f:
            json.dump(stats, f, indent=2)

        # ── Schema ────────────────────────────────────────────────────────────
        # Stamp with generation metadata before writing
        FEATURE_SCHEMA["generated"] = datetime.utcnow().isoformat() + "Z"
        FEATURE_SCHEMA["n_rows"]    = n_rows
        FEATURE_SCHEMA["seed"]      = seed
        FEATURE_SCHEMA["splits"]    = {"train": splits[0], "val": splits[1], "test": splits[2]}
        FEATURE_SCHEMA["delay_rate"]= round(delay_rate, 4)

        with open(os.path.join(out_dir, "cargotrack_delay_schema.json"), "w") as f:
            json.dump(FEATURE_SCHEMA, f, indent=2, ensure_ascii=False)

        self.stdout.write(self.style.SUCCESS(
            f"\nDone. Files written to {os.path.abspath(out_dir)}/\n"
            f"  cargotrack_delay_train.csv   ({len(train):,} rows)\n"
            f"  cargotrack_delay_val.csv     ({len(val):,} rows)\n"
            f"  cargotrack_delay_test.csv    ({len(test):,} rows)\n"
            f"  cargotrack_delay_full.csv    ({n_rows:,} rows)\n"
            f"  cargotrack_delay_schema.json (feature documentation)\n"
            f"  cargotrack_delay_stats.json  (descriptive statistics)\n"
            f"\nDelay rate: {delay_rate:.1%}  |  Seed: {seed}"
        ))
