# Generated by Django 4.2.29 on 2026-04-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('estimated_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['origin', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('CUSTOMS', 'Customs'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed')], default='PENDING', max_length=20)),
                ('carrier_name', models.CharField(max_length=100)),
                ('weight_kg', models.FloatField()),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('delay_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.route')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='shipments_s_trackin_80db53_idx'), models.Index(fields=['status'], name='shipments_s_status_536511_idx')],
            },
        ),
    ]
