"""
cargotrack/cache.py — Cache invalidation helpers.

Import ``invalidate_dashboard_caches`` in any view that mutates shipment,
tracking, alert, or invoice data to bust cached dashboard/analytics responses.
"""
from django.core.cache import cache


CACHE_PATTERNS = [
    # View-level cache keys generated by cache_page use the full URL path.
    # We delete the most specific patterns; cache_page middleware will
    # regenerate on next GET.
    'views.decorators.cache.cache_page.*',
]


def invalidate_dashboard_caches() -> None:
    """Delete all cached dashboard/analytics/shipment pages."""
    cache.delete_pattern('views.decorators.cache.cache_page.*')


def invalidate_cache_for_path(path_prefix: str) -> None:
    """Delete cache entries for a specific URL prefix."""
    cache.delete_pattern(f'views.decorators.cache.cache_page.*{path_prefix}*')
