"""
shipments/serializers.py — DRF serializers for the shipments app
=================================================================

Serializers
-----------
RouteSerializer
    Full read/write serializer for Route objects; validates that distance
    and estimated_hours are positive.

ShipmentSerializer
    Read-only serializer with nested RouteSerializer; used for GET responses.

ShipmentCreateSerializer
    Write serializer for POST /shipments/; tracking_number is auto-generated
    by the view (not accepted from the client).  Validates that scheduled
    departure is before arrival, and that weight is within the 150 000 kg limit.

ShipmentStatusSerializer
    Minimal PATCH serializer that accepts only the ``status`` field, preventing
    accidental overwrite of immutable fields during status transitions.
"""
from rest_framework import serializers
from .models import Route, Shipment

VALID_STATUSES = {s for s, _ in Shipment.STATUS_CHOICES}


class RouteSerializer(serializers.ModelSerializer):
    class Meta:
        model = Route
        fields = [
            'id', 'origin', 'destination',
            'distance_km', 'estimated_hours', 'created_at',
        ]
        read_only_fields = ['id', 'created_at']

    def validate_distance_km(self, value):
        if value <= 0:
            raise serializers.ValidationError("distance_km must be a positive number.")
        return value

    def validate_estimated_hours(self, value):
        if value <= 0:
            raise serializers.ValidationError("estimated_hours must be a positive number.")
        return value

    def validate_origin(self, value):
        if not value.strip():
            raise serializers.ValidationError("Origin cannot be blank.")
        return value.strip()

    def validate_destination(self, value):
        if not value.strip():
            raise serializers.ValidationError("Destination cannot be blank.")
        return value.strip()


class ShipmentSerializer(serializers.ModelSerializer):
    """Full read serializer — nests route for rich GET responses."""

    route          = RouteSerializer(read_only=True)
    status_display = serializers.CharField(source='get_status_display', read_only=True)

    class Meta:
        model = Shipment
        fields = [
            'id', 'tracking_number', 'route', 'status', 'status_display',
            'carrier_name', 'weight_kg',
            'scheduled_departure', 'scheduled_arrival',
            'actual_departure', 'actual_arrival',
            'delay_risk_score', 'created_at', 'updated_at',
        ]
        read_only_fields = ['id', 'tracking_number', 'created_at', 'updated_at']


class ShipmentCreateSerializer(serializers.ModelSerializer):
    """Write serializer for creating a Shipment. tracking_number is auto-generated by the view."""

    class Meta:
        model = Shipment
        fields = [
            'route', 'status', 'carrier_name', 'weight_kg',
            'scheduled_departure', 'scheduled_arrival',
            'actual_departure', 'actual_arrival',
        ]

    def validate_weight_kg(self, value):
        if value <= 0:
            raise serializers.ValidationError("weight_kg must be greater than zero.")
        if value > 150_000:
            raise serializers.ValidationError("weight_kg exceeds the maximum allowed (150 000 kg).")
        return value

    def validate_status(self, value):
        if value not in VALID_STATUSES:
            raise serializers.ValidationError(
                f"Invalid status '{value}'. Must be one of: {', '.join(VALID_STATUSES)}."
            )
        return value

    def validate_carrier_name(self, value):
        if not value.strip():
            raise serializers.ValidationError("carrier_name cannot be blank.")
        return value.strip()

    def validate(self, attrs):
        dep = attrs.get('scheduled_departure')
        arr = attrs.get('scheduled_arrival')
        if dep and arr and dep >= arr:
            raise serializers.ValidationError(
                "scheduled_departure must be before scheduled_arrival."
            )
        act_dep = attrs.get('actual_departure')
        act_arr = attrs.get('actual_arrival')
        if act_dep and act_arr and act_dep >= act_arr:
            raise serializers.ValidationError(
                "actual_departure must be before actual_arrival."
            )
        return attrs


class ShipmentStatusSerializer(serializers.ModelSerializer):
    """Minimal serializer used for PATCH /shipments/<pk>/ (status update only)."""

    class Meta:
        model = Shipment
        fields = ['id', 'tracking_number', 'status']
        read_only_fields = ['id', 'tracking_number']

    def validate_status(self, value):
        if value not in VALID_STATUSES:
            raise serializers.ValidationError(
                f"Invalid status '{value}'. Must be one of: {', '.join(VALID_STATUSES)}."
            )
        return value
