# Generated by Django 4.2.29 on 2026-04-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='alerts_noti_shipmen_9e1a12_idx',
            old_name='alerts_noti_shipmen_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='alerts_noti_read_5cb59e_idx',
            old_name='alerts_noti_read_idx',
        ),
    ]
