# Generated by Django 4.2.29 on 2026-04-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEPARTURE', 'Departure'), ('CHECKPOINT', 'Checkpoint'), ('CUSTOMS_ENTRY', 'Customs Entry'), ('CUSTOMS_CLEAR', 'Customs Clear'), ('ARRIVAL', 'Arrival'), ('DELAY', 'Delay Reported'), ('NOTE', 'Note')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['shipment', 'timestamp'], name='tracking_tr_shipmen_3a6466_idx'), models.Index(fields=['event_type'], name='tracking_tr_event_t_f7f135_idx')],
            },
        ),
    ]
